Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 25

Layout/LineLength:
  Max: 140

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 8

Metrics/ClassLength:
  Exclude:
    - game.rb
    - interface.rb

Layout/EndOfLine:
  Exclude:
    - main.rb
    - user.rb
    - diler.rb
